### ISSUE TITLE
Need data management strategy

### ISSUE THREAD

**Issue by justb4** [Geonovum/ogc-api-testbed#10]
Most of the OGC API services need "data" (except those that are pure proxies, e.g. for a remote WFS) in some form(at): GeoPackage, PostGIS etc. Small datasets can be maintained in GitHub but for bigger datasets and a PostGIS database we need a strategy how to manage that data. It should also be easy for maintainers to add a new dataset together with a service layer. 

Some ideas how to realise data management, from simple to advanced:

- direct file sharing: "Dropbox" like: Next/OwnCloud 
- using a storage server: good experience with Hetzner Storage Box (supports sftp, Samba etc)
- using [Minio](https://min.io) - used e.g. by PDOK - provides download service
- using a "real (geospatial) data server with metadata: 
   * [CKAN](https://ckan.org/) (e.g. used by e.g. https://data.overheid.nl and https://gecatalogus.nl)
   * [GeoNode](https://geonode.org/) - also has GeoServer and future pygeoapi integration
   * GeoNetwork

Needs discussion for best option. Also what a use-case scenario would look like, also in the light of automatic deployment...

**Comment by pvgenuchten** [comment]
A data strategy should be adopted for each service, depending on the use case. Various options are discussed in docs.
