### ISSUE TITLE
Enhance documentation with mkdocs-theme and more content

### ISSUE THREAD

**Issue by justb4** [Geonovum/ogc-api-testbed#11]
#8 added the documentation/landing page as redeployable service.
Next, the actual content of the documentation needs to be improved:

* styling; a suitable [mkdocs Theme](https://www.mkdocs.org/user-guide/styling-your-docs/)
* create structure into chapters/pages
* add content

**Comment by thijsbrentjens** [comment]
@thijsbrentjens creates initial structure
