### ISSUE TITLE
create sandbox and stable demo environment

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/ogc-api-testbed#14]
depends on #2 : after this is done, config 2 environments: 
1. snadbox to play with creation of containers. Geonovum colleagues and others interested should be able to deploy to this
2. stable environment: public demos, limited number of people can administer this environment, deploy/start services

**Comment by thijsbrentjens** [comment]
maybe the best is two servers, to make sure that sandbox changes won't interfer with the stable

**Comment by justb4** [comment]
Think we discussed the use of GitHub ["Branch Protection"](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches).

Think in the simplest case we can have 2 branches and 2 servers (and thus 2 domain names):

- `main` - for the production server
- `sandbox` - for the Sandbox environment

We can make `main` a protected branch, simplest is to only allow specific users to push, but there are more elaborate configs possible.  `sandbox` branch will be unrestricted for any users with commit rights on this repo. 

2 servers coupled to 2 branches is very well possible with Ansible and thus the GH Workflows: Ansible has the concept of an [Inventory](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html) basically the hosts on which to perform actions (`-i` option). We already have a `prod` inventory, see:

* [GH Action](https://github.com/Geonovum/ogc-api-testbed/blob/main/.github/workflows/deploy.pygeoapi.yml#L28)
* [Ansible Inventory file prod.yml](https://github.com/Geonovum/ogc-api-testbed/blob/main/ansible/hosts/prod.yml) - encrypted with Ansible Vault and put in GH Secret. (Though maybe that info can be public as it is just the server domain name, no passwords or such).

Think if we first get all services running via `main`, it is time for a `sandbox` branch.

**Comment by thijsbrentjens** [comment]
@thijsbrentjens will order a second server, @justb4 if this server is ready, could you do the rest then?

**Comment by justb4** [comment]
> @thijsbrentjens will order a second server, @justb4 if this server is ready, could you do the rest then?

ok

**Comment by thijsbrentjens** [comment]
as discussed with @justb4: better a separate, dedicated repo for the sandbox to avoid accidental deployment and to keep things clear in scripts and config files.

Also for access management to github easier.

**Comment by pvgenuchten** [comment]
done
