### ISSUE TITLE
move docs to github/docs

### ISSUE THREAD

**Issue by pvgenuchten** [Geonovum/ogc-api-testbed#19]
in stead of running it as a service, let git-action deploy as html on geonovum.github.io/ogc-api-testbed/docs

By @justb4:

Yes, in addition it is quite easy to run "docs" as a GitHub Pages flat HTML website in its own domain. We use this e.g. for pygeoapi.io and tv.osgeo.nl . So this needs to be done:

- [x] move docs from `services/docs` to GH root /docs
- [x] make new service "home" that is just a one-page index.md landing page with links to the services and the new docs site, make required Ansible and Actions changes
- [x] DNS: create a CNAME entry e.g. apitestdocs.geonovum.nl that refers to geonovum.github.io
- [x] GitHub create GH Pages entry with CNAME
- [x] GitHub add GH Action file to publish docs to GitHub, use [pygeoapi.io main.yml as starter](https://github.com/geopython/pygeoapi.io/blob/master/.github/workflows/main.yml)
- [x] anything else? See https://github.com/geopython/pygeoapi.io

Advantages:

- docs are always available even when VPS-es gone
- single authoritative place for documentation (i.s.o. both in stable and sandbox servers)

**Comment by thijsbrentjens** [comment]
good proposal, I'll asl for a CNAME entry

**Comment by thijsbrentjens** [comment]
CNAME entry should be there: apitestdocs.geonovum.nl --> geonovum.github.io

**Comment by justb4** [comment]
done
