### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/ogc-api-testbed#23]
Ideally, we should have a permissive open source license, for the re-use of the code / docs here

**Comment by pvgenuchten** [comment]
Suggestion: 
- MIT for code
- CC-by for docs

**Comment by justb4** [comment]
Looks good, though I mostly use GNU GPL v3 and CC-by (docs). But is up to Geonovum. I'lll be happy with MIT then.

**Comment by pvgenuchten** [comment]
thijs decides, paul implements

**Comment by thijsbrentjens** [comment]
docs: CC-by 4.0
code: MIT licentie

**Comment by justb4** [comment]
Done.
