### ISSUE TITLE
docs: add workflow diagrams

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/ogc-api-testbed#31]
for deployment of services and dependencies

**Comment by pvgenuchten** [comment]
What do you have in mind Thijs? 

For example GHC, which contains 3 elements:
- UI
- Runner
- Database

Or more in detail, geoserver having the OGC API Extension, Configuration via mounted volume, etc?

Or more operational, which steps involved to deploy a service?

**Comment by pvgenuchten** [comment]
I added a schematic overview at https://apitestdocs.geonovum.nl/setup/platform/, is this what you are looking for?

**Comment by justb4** [comment]
This was discussed at last's week workshop: "workflow" here is meant as the interaction initiated by the end-user from a GH commit up to deployment. More or less like an UML interaction diagram. The entities are User and the interacting CI/CD components: GitHub Action, Ansible, Server VM, Docker. At least a graphical representation of the actions after GH commit.

**Comment by pvgenuchten** [comment]
more like this?
<img width="681" alt="image" src="https://user-images.githubusercontent.com/299829/123765009-9e3eba00-d8c5-11eb-9cf0-03e668fd9e6f.png">

**Comment by pvgenuchten** [comment]
Use above image, but 
Add that traeffik is the gateway to outside

**Comment by pvgenuchten** [comment]
Draw a box around github+ansible (this happens on git)
